import { NewsSourceConfig } from "../types/article";

export const NEWS_SOURCES: NewsSourceConfig[] = [
  {
    id: "guardian",
    name: "The Guardian",
    provider: "guardian-search",
    apiKeyEnvVar: "GUARDIAN_API_KEY",
    apiKey: process.env.GUARDIAN_API_KEY ?? "your-guardian-api-key",
    baseUrl: "https://content.guardianapis.com",
  },
  {
    id: "nyt",
    name: "New York Times",
    provider: "nyt-top-stories",
    apiKeyEnvVar: "NYT_NEWS_API_KEY",
    apiKey: process.env.NYT_NEWS_API_KEY ?? "your-nyt-news-api-key",
    apiUrlEnvVar: "NYT_NEWS_API_URL",
    apiUrl:
      process.env.NYT_NEWS_API_URL ??
      "https://api.nytimes.com/svc/topstories/v2/home.json",
    baseUrl: "https://api.nytimes.com",
  },
  {
    id: "nyt-most-popular",
    name: "New York Times - Most Popular",
    provider: "nyt-most-popular",
    apiKeyEnvVar: "NYT_NEWS_API_KEY",
    apiKey: process.env.NYT_NEWS_API_KEY ?? "your-nyt-news-api-key",
    apiUrlEnvVar: "NYT_MOST_POPULAR_API_URL",
    apiUrl:
      process.env.NYT_MOST_POPULAR_API_URL ??
      "https://api.nytimes.com/svc/mostpopular/v2/viewed/1.json",
    baseUrl: "https://api.nytimes.com",
  },
  {
    id: "bbc",
    name: "BBC News",
    provider: "rss-feed",
    baseUrl: "https://www.bbc.com",
    rssUrlEnvVar: "BBC_NEWS_RSS_URL",
    rssUrl: process.env.BBC_NEWS_RSS_URL ?? "https://feeds.bbci.co.uk/news/rss.xml",
  },
  {
    id: "reuters",
    name: "Reuters",
    provider: "rss-feed",
    baseUrl: "https://www.reuters.com",
    rssUrlEnvVar: "REUTERS_RSS_URL",
    rssUrl: process.env.REUTERS_RSS_URL ?? "https://feeds.reuters.com/reuters/topNews",
    rssUrlFallbacks: [
      "https://www.reuters.com/rssFeed/topNews",
      "https://www.reuters.com/rssFeed/worldNews",
      "https://www.reuters.com/rssFeed/businessNews",
    ],
  },
  {
    id: "abc",
    name: "ABC News (AU)",
    provider: "rss-feed",
    baseUrl: "https://www.abc.net.au",
    rssUrlEnvVar: "ABC_NEWS_RSS_URL",
    rssUrl: process.env.ABC_NEWS_RSS_URL ?? "https://www.abc.net.au/news/feed/51120/rss.xml",
  },
  {
    id: "sbs",
    name: "SBS News",
    provider: "rss-feed",
    baseUrl: "https://www.sbs.com.au",
    rssUrlEnvVar: "SBS_NEWS_RSS_URL",
    rssUrl: process.env.SBS_NEWS_RSS_URL ?? "https://www.sbs.com.au/news/podcastfeeds/news.rss",
  },
  {
    id: "cnn",
    name: "CNN",
    provider: "rss-feed",
    baseUrl: "https://www.cnn.com",
    rssUrlEnvVar: "CNN_NEWS_RSS_URL",
    rssUrl: process.env.CNN_NEWS_RSS_URL ?? "http://rss.cnn.com/rss/cnn_topstories.rss",
  },
  {
    id: "npr",
    name: "NPR",
    provider: "rss-feed",
    baseUrl: "https://www.npr.org",
    rssUrlEnvVar: "NPR_NEWS_RSS_URL",
    rssUrl: process.env.NPR_NEWS_RSS_URL ?? "https://www.npr.org/rss/rss.php?id=1001",
  },
  {
    id: "google-news-world",
    name: "Google News (World)",
    provider: "rss-feed",
    baseUrl: "https://news.google.com",
    rssUrlEnvVar: "GOOGLE_NEWS_WORLD_RSS_URL",
    rssUrl:
      process.env.GOOGLE_NEWS_WORLD_RSS_URL ??
      "https://news.google.com/atom/topics/CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx1YlY4U0JXVnVMVWRDR2dKSlRpZ0FQAQ?hl=en-US&gl=US&ceid=US:en&oc=11",
  },
  {
    id: "foxnews",
    name: "Fox News",
    provider: "rss-feed",
    baseUrl: "https://www.foxnews.com",
    rssUrlEnvVar: "FOXNEWS_RSS_URL",
    rssUrl: process.env.FOXNEWS_RSS_URL ?? "http://feeds.foxnews.com/foxnews/latest",
  },
  {
    id: "buzzfeed-world",
    name: "BuzzFeed World",
    provider: "rss-feed",
    baseUrl: "https://www.buzzfeed.com",
    rssUrlEnvVar: "BUZZFEED_WORLD_RSS_URL",
    rssUrl: process.env.BUZZFEED_WORLD_RSS_URL ?? "https://www.buzzfeed.com/in/world.xml",
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    provider: "rss-feed",
    baseUrl: "https://techcrunch.com",
    rssUrlEnvVar: "TECHCRUNCH_RSS_URL",
    rssUrl:
      process.env.TECHCRUNCH_RSS_URL ?? "https://techcrunch.com/feed/",
  },
  {
    id: "guardian-au",
    name: "The Guardian Australia",
    provider: "rss-feed",
    baseUrl: "https://www.theguardian.com",
    rssUrlEnvVar: "GUARDIAN_AU_RSS_URL",
    rssUrl: process.env.GUARDIAN_AU_RSS_URL ?? "https://www.theguardian.com/au/rss",
  },
  {
    id: "smh",
    name: "Sydney Morning Herald",
    provider: "rss-feed",
    baseUrl: "https://www.smh.com.au",
    rssUrlEnvVar: "SMH_NEWS_RSS_URL",
    rssUrl: process.env.SMH_NEWS_RSS_URL ?? "https://www.smh.com.au/rss/feed.xml",
  },
  {
    id: "theage",
    name: "The Age",
    provider: "rss-feed",
    baseUrl: "https://www.theage.com.au",
    rssUrlEnvVar: "THEAGE_NEWS_RSS_URL",
    rssUrl: process.env.THEAGE_NEWS_RSS_URL ?? "https://www.theage.com.au/rss/feed.xml",
  },
  {
    id: "ninetynine",
    name: "9News",
    provider: "rss-feed",
    baseUrl: "https://www.9news.com.au",
    rssUrlEnvVar: "NINE_NEWS_RSS_URL",
    rssUrl: process.env.NINE_NEWS_RSS_URL ?? "https://www.9news.com.au/rss",
  },
  {
    id: "theaustralian",
    name: "The Australian",
    provider: "rss-feed",
    baseUrl: "https://www.theaustralian.com.au",
    rssUrlEnvVar: "THE_AUSTRALIAN_RSS_URL",
    rssUrl: process.env.THE_AUSTRALIAN_RSS_URL ?? "https://www.theaustralian.com.au/rss",
  },
  {
    id: "canberra-times",
    name: "The Canberra Times",
    provider: "rss-feed",
    baseUrl: "https://www.canberratimes.com.au",
    rssUrlEnvVar: "CANBERRA_TIMES_RSS_URL",
    rssUrl: process.env.CANBERRA_TIMES_RSS_URL ?? "https://www.canberratimes.com.au/rss.xml",
  },
  {
    id: "brisbane-times",
    name: "Brisbane Times",
    provider: "rss-feed",
    baseUrl: "https://www.brisbanetimes.com.au",
    rssUrlEnvVar: "BRISBANE_TIMES_RSS_URL",
    rssUrl: process.env.BRISBANE_TIMES_RSS_URL ?? "https://www.brisbanetimes.com.au/rss/feed.xml",
  },
  {
    id: "watoday",
    name: "WAtoday",
    provider: "rss-feed",
    baseUrl: "https://www.watoday.com.au",
    rssUrlEnvVar: "WATODAY_RSS_URL",
    rssUrl: process.env.WATODAY_RSS_URL ?? "https://www.watoday.com.au/rss/feed.xml",
  },
  {
    id: "crikey",
    name: "Crikey",
    provider: "rss-feed",
    baseUrl: "https://www.crikey.com.au",
    rssUrlEnvVar: "CRIKEY_RSS_URL",
    rssUrl: process.env.CRIKEY_RSS_URL ?? "https://www.crikey.com.au/feed/",
  },
  {
    id: "west-australian",
    name: "The West Australian",
    provider: "rss-feed",
    baseUrl: "https://thewest.com.au",
    rssUrlEnvVar: "WEST_AUSTRALIAN_RSS_URL",
    rssUrl: process.env.WEST_AUSTRALIAN_RSS_URL ?? "https://thewest.com.au/rss",
  },
  {
    id: "news-com-au",
    name: "News.com.au",
    provider: "rss-feed",
    baseUrl: "https://www.news.com.au",
    rssUrlEnvVar: "NEWS_COM_AU_RSS_URL",
    rssUrl: process.env.NEWS_COM_AU_RSS_URL ?? "https://www.news.com.au/content-feeds/latest-news-national/",
  },
  {
    id: "businessnews",
    name: "Business News",
    provider: "rss-feed",
    baseUrl: "https://www.businessnews.com.au",
    rssUrlEnvVar: "BUSINESS_NEWS_RSS_URL",
    rssUrl: process.env.BUSINESS_NEWS_RSS_URL ?? "https://www.businessnews.com.au/rssfeed/latest.rss",
  },
  {
    id: "the-shovel",
    name: "The Shovel",
    provider: "rss-feed",
    baseUrl: "https://theshovel.com.au",
    rssUrlEnvVar: "THE_SHOVEL_RSS_URL",
    rssUrl: process.env.THE_SHOVEL_RSS_URL ?? "https://theshovel.com.au/feed/",
  },
  {
    id: "independent-australia",
    name: "Independent Australia",
    provider: "rss-feed",
    baseUrl: "https://independentaustralia.net",
    rssUrlEnvVar: "INDEPENDENT_AUSTRALIA_RSS_URL",
    rssUrl: process.env.INDEPENDENT_AUSTRALIA_RSS_URL ?? "https://feeds.feedburner.com/IndependentAustralia",
  },
  {
    id: "tech-business-news",
    name: "Tech Business News",
    provider: "rss-feed",
    baseUrl: "https://www.techbusinessnews.com.au",
    rssUrlEnvVar: "TECH_BUSINESS_NEWS_RSS_URL",
    rssUrl: process.env.TECH_BUSINESS_NEWS_RSS_URL ?? "https://www.techbusinessnews.com.au/feed/",
  },
  {
    id: "newsagency-blog",
    name: "Australian Newsagency Blog",
    provider: "rss-feed",
    baseUrl: "https://www.newsagencyblog.com.au",
    rssUrlEnvVar: "NEWSAGENCY_BLOG_RSS_URL",
    rssUrl: process.env.NEWSAGENCY_BLOG_RSS_URL ?? "https://www.newsagencyblog.com.au/feed/",
  },
  {
    id: "ozzie-news",
    name: "Ozzie News",
    provider: "rss-feed",
    baseUrl: "https://ozzienews.com",
    rssUrlEnvVar: "OZZIE_NEWS_RSS_URL",
    rssUrl: process.env.OZZIE_NEWS_RSS_URL ?? "https://ozzienews.com/feed/",
  },
  {
    id: "cairns-news",
    name: "Cairns News",
    provider: "rss-feed",
    baseUrl: "https://cairnsnews.org",
    rssUrlEnvVar: "CAIRNS_NEWS_RSS_URL",
    rssUrl: process.env.CAIRNS_NEWS_RSS_URL ?? "https://cairnsnews.org/feed/",
  },
  {
    id: "sixteen-news",
    name: "16 News",
    provider: "rss-feed",
    baseUrl: "http://www.16news.com.au",
    rssUrlEnvVar: "SIXTEEN_NEWS_RSS_URL",
    rssUrl: process.env.SIXTEEN_NEWS_RSS_URL ?? "http://www.16news.com.au/?feed=rss2",
  },
  {
    id: "kalkine-media",
    name: "Kalkine Media",
    provider: "rss-feed",
    baseUrl: "https://kalkinemedia.com/au",
    rssUrlEnvVar: "KALKINE_MEDIA_RSS_URL",
    rssUrl: process.env.KALKINE_MEDIA_RSS_URL ?? "https://kalkinemedia.com/au/feed",
  },
  {
    id: "ibtimes-au",
    name: "International Business Times AU",
    provider: "rss-feed",
    baseUrl: "https://www.ibtimes.com.au",
    rssUrlEnvVar: "IBTIMES_AU_RSS_URL",
    rssUrl: process.env.IBTIMES_AU_RSS_URL ?? "https://www.ibtimes.com.au/rss",
  },
  {
    id: "werribee-news",
    name: "The Werribee News",
    provider: "rss-feed",
    baseUrl: "https://www.werribeenews.com.au",
    rssUrlEnvVar: "WERRIBEE_NEWS_RSS_URL",
    rssUrl: process.env.WERRIBEE_NEWS_RSS_URL ?? "https://www.werribeenews.com.au/feed/",
  },
  {
    id: "sydney-sun",
    name: "Sydney Sun",
    provider: "rss-feed",
    baseUrl: "https://www.sydneysun.com",
    rssUrlEnvVar: "SYDNEY_SUN_RSS_URL",
    rssUrl: process.env.SYDNEY_SUN_RSS_URL ?? "http://feeds.sydneysun.com/rss/ae0def0d9b645403",
  },
  {
    id: "perth-herald",
    name: "Perth Herald",
    provider: "rss-feed",
    baseUrl: "https://www.perthherald.com",
    rssUrlEnvVar: "PERTH_HERALD_RSS_URL",
    rssUrl: process.env.PERTH_HERALD_RSS_URL ?? "http://feeds.perthherald.com/rss/12878be9fc2ca79c",
  },
  {
    id: "heraldsun",
    name: "Herald Sun",
    provider: "rss-feed",
    baseUrl: "https://www.heraldsun.com.au",
    rssUrlEnvVar: "HERALD_SUN_RSS_URL",
    rssUrl: process.env.HERALD_SUN_RSS_URL ?? "https://www.heraldsun.com.au/news/national/rss",
  },
  {
    id: "skynews-au",
    name: "Sky News Australia",
    provider: "rss-feed",
    baseUrl: "https://www.skynews.com.au",
    rssUrlEnvVar: "SKYNEWS_AU_RSS_URL",
    rssUrl: process.env.SKYNEWS_AU_RSS_URL ?? "https://www.skynews.com.au/rss/article.xml",
  },
  {
    id: "theconversation",
    name: "The Conversation (AU)",
    provider: "rss-feed",
    baseUrl: "https://theconversation.com",
    rssUrlEnvVar: "THE_CONVERSATION_RSS_URL",
    rssUrl: process.env.THE_CONVERSATION_RSS_URL ?? "https://theconversation.com/au/articles.rss",
  },
  {
    id: "afr",
    name: "Australian Financial Review",
    provider: "rss-feed",
    baseUrl: "https://www.afr.com",
    rssUrlEnvVar: "AFR_RSS_URL",
    rssUrl: process.env.AFR_RSS_URL ?? "https://www.afr.com/rss",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera",
    provider: "rss-feed",
    baseUrl: "https://www.aljazeera.com",
    rssUrlEnvVar: "ALJAZEERA_RSS_URL",
    rssUrl: process.env.ALJAZEERA_RSS_URL ?? "https://www.aljazeera.com/xml/rss/all.xml",
  },
  {
    id: "guardian-us",
    name: "The Guardian (US)",
    provider: "rss-feed",
    baseUrl: "https://www.theguardian.com",
    rssUrlEnvVar: "GUARDIAN_US_RSS_URL",
    rssUrl: process.env.GUARDIAN_US_RSS_URL ?? "https://www.theguardian.com/us/rss",
  },
  {
    id: "washingtonpost",
    name: "Washington Post",
    provider: "rss-feed",
    baseUrl: "https://www.washingtonpost.com",
    rssUrlEnvVar: "WP_RSS_URL",
    rssUrl: process.env.WP_RSS_URL ?? "http://feeds.washingtonpost.com/rss/rss_election-2012",
  },
  {
    id: "financialtimes",
    name: "Financial Times",
    provider: "rss-feed",
    baseUrl: "https://www.ft.com",
    rssUrlEnvVar: "FT_RSS_URL",
    rssUrl: process.env.FT_RSS_URL ?? "https://www.ft.com/?format=rss",
  },
  {
    id: "ap",
    name: "Associated Press",
    provider: "rss-feed",
    baseUrl: "https://apnews.com",
    rssUrlEnvVar: "AP_RSS_URL",
    rssUrl: process.env.AP_RSS_URL ?? "https://apnews.com/hub/ap-top-news/rss",
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    provider: "rss-feed",
    baseUrl: "https://www.bloomberg.com",
    rssUrlEnvVar: "BLOOMBERG_RSS_URL",
    rssUrl: process.env.BLOOMBERG_RSS_URL ?? "https://www.bloomberg.com/feed/podcast/etf-report.xml",
  },
  {
    id: "lemonde",
    name: "Le Monde",
    provider: "rss-feed",
    baseUrl: "https://www.lemonde.fr",
    rssUrlEnvVar: "LEMONDE_RSS_URL",
    rssUrl: process.env.LEMONDE_RSS_URL ?? "https://www.lemonde.fr/rss/une.xml",
  },
  {
    id: "spiegel",
    name: "Der Spiegel",
    provider: "rss-feed",
    baseUrl: "https://www.spiegel.de",
    rssUrlEnvVar: "SPIEGEL_RSS_URL",
    rssUrl: process.env.SPIEGEL_RSS_URL ?? "https://www.spiegel.de/schlagzeilen/tops/index.rss",
  },
  {
    id: "elpais",
    name: "El País",
    provider: "rss-feed",
    baseUrl: "https://elpais.com",
    rssUrlEnvVar: "ELPAIS_RSS_URL",
    rssUrl: process.env.ELPAIS_RSS_URL ?? "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
  },
  {
    id: "scmp",
    name: "South China Morning Post",
    provider: "rss-feed",
    baseUrl: "https://www.scmp.com",
    rssUrlEnvVar: "SCMP_RSS_URL",
    rssUrl: process.env.SCMP_RSS_URL ?? "https://www.scmp.com/rss/asia-briefing-news/rss.xml",
  },
  {
    id: "dw",
    name: "Deutsche Welle",
    provider: "rss-feed",
    baseUrl: "https://www.dw.com",
    rssUrlEnvVar: "DW_RSS_URL",
    rssUrl: process.env.DW_RSS_URL ?? "https://rss.dw.com/rdf/rss-en-all",
  },
  {
    id: "france24",
    name: "France 24",
    provider: "rss-feed",
    baseUrl: "https://www.france24.com",
    rssUrlEnvVar: "FRANCE24_RSS_URL",
    rssUrl: process.env.FRANCE24_RSS_URL ?? "https://www.france24.com/en/rss",
  },
  {
    id: "euronews",
    name: "Euronews",
    provider: "rss-feed",
    baseUrl: "https://www.euronews.com",
    rssUrlEnvVar: "EURONEWS_RSS_URL",
    rssUrl: process.env.EURONEWS_RSS_URL ?? "https://www.euronews.com/rss",
  },
  {
    id: "cbc",
    name: "CBC News (World)",
    provider: "rss-feed",
    baseUrl: "https://www.cbc.ca",
    rssUrlEnvVar: "CBC_WORLD_RSS_URL",
    rssUrl: process.env.CBC_WORLD_RSS_URL ?? "https://www.cbc.ca/cmlink/rss-world",
  },
  {
    id: "cna",
    name: "Channel NewsAsia",
    provider: "rss-feed",
    baseUrl: "https://www.channelnewsasia.com",
    rssUrlEnvVar: "CNA_RSS_URL",
    rssUrl:
      process.env.CNA_RSS_URL ??
      "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
  },
  {
    id: "csmonitor",
    name: "Christian Science Monitor",
    provider: "rss-feed",
    baseUrl: "https://www.csmonitor.com",
    rssUrlEnvVar: "CSMONITOR_RSS_URL",
    rssUrl: process.env.CSMONITOR_RSS_URL ?? "https://rss.csmonitor.com/feeds/world",
  },
  {
    id: "rfi",
    name: "RFI",
    provider: "rss-feed",
    baseUrl: "https://www.rfi.fr",
    rssUrlEnvVar: "RFI_RSS_URL",
    rssUrl: process.env.RFI_RSS_URL ?? "https://www.rfi.fr/en/rss",
  },
  {
    id: "time",
    name: "Time",
    provider: "rss-feed",
    baseUrl: "https://time.com",
    rssUrlEnvVar: "TIME_RSS_URL",
    rssUrl: process.env.TIME_RSS_URL ?? "https://time.com/feed/",
  },
];

export const isPlaceholderSecret = (value: string | undefined): boolean => {
  if (!value) {
    return true;
  }

  const normalized = value.trim().toLowerCase();
  return (
    normalized.length === 0 ||
    normalized.startsWith("your-") ||
    normalized.includes("placeholder")
  );
};

export const isSourceConfigured = (source: NewsSourceConfig): boolean => {
  if (source.provider === "rss-feed") {
    return !isPlaceholderSecret(source.rssUrl);
  }

  const keyOk = source.apiKey ? !isPlaceholderSecret(source.apiKey) : true;
  const urlOk = source.apiUrl ? !isPlaceholderSecret(source.apiUrl) : true;
  return keyOk && urlOk;
};
